# Generated by Django 4.2.16 on 2024-10-21 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_bought_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bought_books',
        ),
    ]
