# Generated by Django 4.2.16 on 2024-10-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_discount_percent'),
        ('accounts', '0010_remove_profile_bought_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bought_books',
            field=models.ManyToManyField(blank=True, to='books.book'),
        ),
    ]
