# Generated by Django 4.2.16 on 2024-11-08 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_remove_book_epub_file_book_pdf_file'),
        ('accounts', '0016_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wishlisted_books',
            field=models.ManyToManyField(blank=True, related_name='wishlisted_by', to='books.book'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bought_books',
            field=models.ManyToManyField(blank=True, related_name='buyers', to='books.book'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
