# Generated by Django 4.2.16 on 2024-11-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_review_parent_alter_review_rating'),
        ('accounts', '0017_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='seen_discounted_books',
            field=models.ManyToManyField(blank=True, related_name='seen_by', to='books.book'),
        ),
        migrations.AddField(
            model_name='profile',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlisted_by', to='books.book'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bought_books',
            field=models.ManyToManyField(blank=True, related_name='buyers', to='books.book'),
        ),
    ]
