# Generated by Django 4.2.16 on 2024-11-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_remove_book_epub_file_book_pdf_file'),
        ('accounts', '0018_rename_wishlisted_books_profile_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='seen_discounted_books',
            field=models.ManyToManyField(blank=True, related_name='seen_by', to='books.book'),
        ),
    ]
