# Generated by Django 4.2.16 on 2024-11-12 05:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_profile_seen_discounted_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_discount_check',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
