# Generated by Django 4.2.16 on 2024-11-26 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_alter_book_author_alter_book_category'),
        ('accounts', '0021_remove_profile_is_18'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_18',
            field=models.ManyToManyField(blank=True, related_name='18+', to='books.book'),
        ),
    ]
