# Generated by Django 4.2.16 on 2024-09-27 08:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, default=None, max_length=500)),
                ('price', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_percent', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(100)])),
                ('image_url', models.CharField(blank=True, default='', max_length=2083)),
                ('thumbnail_image_url', models.CharField(blank=True, default='', max_length=2083)),
            ],
        ),
    ]
