# Generated by Django 4.2.16 on 2024-09-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_category_alter_book_author_alter_book_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bestseller',
            field=models.BooleanField(default=False),
        ),
    ]
