# Generated by Django 4.2.16 on 2024-10-01 07:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_bestseller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='discount_percent',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
