# Generated by Django 4.2.16 on 2024-11-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_review_parent_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
    ]
